version: '2'
services:

  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/etc/salt:/etc/salt
    environment:
      - "SSLAB=0.1"
    command:
      - /usr/bin/salt-minion
    links:
      - master
    networks:
      - sELKp

networks:
  saltOS:
    driver: bridge
